### ISSUE TITLE
Installation of newest version issues

### ISSUE THREAD

**Issue by tbrunetti** [Santy-8128/DosageConvertor#2]
I am having problems with installing the new version of DosageConvertor. Despite having cmake, make, and cget installed, I continue to see the following error:
```
-e Installing Dependencies - Libstatgen ...
-e Generating MakeFiles ...
CMake Error at /usr/local/share/cmake-3.13/Modules/CMakeDetermineSystem.cmake:100 (message):
 Could not find toolchain file: ../cget/cget/cget.cmake
Call Stack (most recent call first):
 CMakeLists.txt:2 (project)CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.
Binary created at /release-build/DosageConvertor
```

I have tried exporting $CMAKE_MAKE_PROGRAM with the path to my make file executable but it continues to have this error.  Any suggestions?  I don't recall previous versions having problems with installation?

Also, this seems to just be a problem on Mac OSX.  I am able to install fine on Linux

Update:  Acutally this is resolved if you reinstall gcc, however, still now theds is an Open MP library problem due to weird compatibility issues with Mac OSX library gcc.  But it works now.

**Comment by hrafnfaedhir** [comment]
I am receiving the same error on install.  I am using MacOSX 10.14.4. I updated gcc ( and reinstalled it).  Installed cmake, and cget.  But still receive the same errors.  Do you have any suggestions of what to try next?

 bash install.sh
Installing Dependencies - Libstatgen ...
Generating MakeFiles ...
CMake Error at /usr/local/Cellar/cmake/3.14.4/share/cmake/Modules/CMakeDetermineSystem.cmake:99 (message):
  Could not find toolchain file: ../cget/cget/cget.cmake
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)


CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
make: *** No targets specified and no makefile found.  Stop.
Binary created at /release-build/DosageConvertor

**Comment by jonathonl** [comment]
I'm assuming that you have an error message in install.log. Can you please provide that message?
